### ISSUE TITLE
Currency delay

### ISSUE THREAD

**Issue by Homaxz** [ls-/ls_Toasts#10]
Not sure if this is a bug or a design choice, but whenever I gain a currency (Order Resources for example) it will show a few seconds after obtaining.

I've disabled the "DND" feature thinking it might be combat related, but that didn't solve it. 

This also happens when Currency is the only Toast being displayed, for example picking up Garrison Resources from WoD's Garrison Cache. 

This is happening with v1.11 and v1.12, and no other addons enabled.

**Comment by ls-** [comment]
That's Blizz "feature", CHAT_MSG_CURRENCY event lags like a mofo... Can't be helped 😢

**Comment by Homaxz** [comment]
I see, thanks for clarifying. :-)
