### ISSUE TITLE
Missing item text on appearance toasts

### ISSUE THREAD

**Issue by Homaxz** [ls-/ls_Toasts#12]
http://i.imgur.com/pRKXXyK.jpg

I've noticed this here, every time I get more than 1 appearance added, on some item the text won't show.
Using 1.15

**Comment by ls-** [comment]
Yeah, I get it too... I know why it happens, but I haven't found a way to fix it yet...

It happens, cuz information isn't cached yet, so addon fails to parse needed data, appearance link and name T_T

But I'm testing a workaround atm, so it'll be fixed, dunno when though...

**Comment by ls-** [comment]
Fixed 👍
