### ISSUE TITLE
ElvUI achievement tab

### ISSUE THREAD

**Issue by Homaxz** [ls-/ls_Toasts#13]
Having an odd issue when using this with ElvUI, parts of the achievement skin aren't working, 

standard ElvUI: http://i.imgur.com/qrO8aJh.jpg

ElvUI + ls_Toasts: http://i.imgur.com/JRg6aW8.jpg

As you can see, the achivement frame itself isn't skinned anymore, as well as some sliders and dropdowns.

Is this something you can fix, or do I need to contact ElvUI authors about this?

Thanks for your great work!

**Comment by ls-** [comment]
I think I know why it happens...

**Comment by ls-** [comment]
Fixed.
