### ISSUE TITLE
Lua Error at the end of dungeon

### ISSUE THREAD

**Issue by Juggerone** [ls-/ls_Toasts#15]
Hello, 

It seems the addon it returns a lua error when I complete tank call to arms (satchel) dungeons.

`Message: Interface\AddOns\ls_Toasts\ls_Toasts.lua:931: attempt to call method 'SetLFGCompletionReward' (a nil value)

**Comment by ls-** [comment]
Hi!
It's already fixed by https://github.com/ls-/ls_Toasts/commit/344171d4bbf75f13d41db5725a92935f22b1256c commit. However, I haven't released new version yet, cuz I'm quite busy IRL atm.

Closing it, cuz it's fixed :p
