### ISSUE TITLE
Possible QuestTalkingHeadFrame bug and toasts.

### ISSUE THREAD

**Issue by xt9** [ls-/ls_Toasts#16]
While tailoring my new UI I decided it would be best to move QuestTalkingHeadFrame  with Moveanything to the  center left corner because it's in the way on it's original position, while trying this out it became clear to me that the worldquest reward toasts were anchored to QuestTalkingHeadFrame  in some way (because it started out in the middle, then popped up over QuestTalkingHeadFrame  as soon as it appeared)

**Pictured: http://cubeupload.com/im/QRLeEm.jpg**

A friend recommended lstoasts because it had one single controllable anchor, but it still seems to clash with this behavior. 

**Pictured: http://cubeupload.com/im/2d59Dr.jpg (the anchor is supposed to be at the bottom here)**
**Anchor: http://cubeupload.com/im/X21jfE.jpg (it does not fix itself after a /reload)**

I shall reinstall and reload after configuring, because I'm not sure i did the first time around. But it seems that the anchor is "corrupted" after being logged in for a while.
I'm not sure that this is an Issue with lstoasts, but i thought that I should share with you either way.

**Comment by ls-** [comment]
Sup!

Did you try disabling move anything? o_O I think that something resets `TOPLEFT` point of anchor frame to that position, meanwhile my addon sets `BOTTOMLEFT` point to where it's supposed to be :p 

BTW, if you haven't reset your options yet, could you run `/dump ls_Toasts[2].point` script, and tell me what it dumps into your chat window?

**Comment by xt9** [comment]
[4]=38,
[3]="TOPLEFT",
[2]="UIParent",
[1]="TOPLEFT",

These were after a reload, and turning in an emissary cache, and the anchor did not look corrupted anymore, but it had moved to the top left corner.

I'll update you after a reinstall and playing for a while.

**Comment by ls-** [comment]
Hm, there should be 5 entries, but I guess it's copy-paste fail, looks fine though.

I think it's a conflict w/ some other addon T_T Hate when it happens...

**Comment by xt9** [comment]
It's probably another addon yeah, it worked fine for an hour then things got... wierd.
This is after a reinstall of lstoasts, but i never disabled MoveAnything

**Anchor + dump: http://cubeupload.com/im/4oSf8g.jpg**

**Comment by ls-** [comment]
Wow o_O Did it happen on its own? o_O

I'll my anchor frame to that spot and will see what happens :p

**Comment by xt9** [comment]
The symptom was a relog, I saw the tank call to arms was up so i logged my druid, The class hall mission popped up in the top left corner so i checked the anchor, and there it was.

**Comment by ls-** [comment]
K, thank you!

It's a bug, now I need to figure out how to fix it, there's a bug in my preset system :p

**Comment by ls-** [comment]
Fixed. Will release an update a bit later today.

**Comment by xt9** [comment]
Cool :)
