### ISSUE TITLE
Cannot access options

### ISSUE THREAD

**Issue by amiyuy** [ls-/ls_Toasts#17]
I see you tried to address this before, but I cannot see your options menu.  I use SUF instead of the default raid frames.

Fresh install of version 1.23 via the Curse Client.

/lstoasts opens the options window, but ls_Toasts is not listed.

![image](https://cloud.githubusercontent.com/assets/3958649/23092227/0281bcf2-f57b-11e6-85d6-ea058eb69a3c.png)

**Comment by ls-** [comment]
Sup!

I'll release an update a bit later today that should address this "issue". If you don't want to wait you can download ls: Toasts from [GH](https://github.com/ls-/ls_Toasts/archive/master.zip).

On a side note, ls: Toasts entry appears at the bottom of the list, cuz name has coloured `ls:` in it, but I'll change it in v1.24 :p

**Comment by ls-** [comment]
"Fixed" in [1.24](https://github.com/ls-/ls_Toasts/releases/tag/1.24).
