### ISSUE TITLE
Request: Notification Throttling/Spam Control

### ISSUE THREAD

**Issue by Funsponge** [ls-/ls_Toasts#19]
Foxflower from the random fox that spawns can generate 20-30 toasts in a few seconds. Would be cool if it were possible to display a running total on a single toast as I loot multiple foxflower. Another example would be ancient mana in Suramar.

**Comment by ls-** [comment]
Hi.

K, bad news first. There's no way to check if you looted multiple items w/ the same ID (that's your case) or the same item popped up in two different events, e.g. `SHOW_LOOT_TOAST` and `CHAT_MSG_LOOT`, items don't have any kind of GUIDs.

But here's good news! In my local builds I combine all items w/ the same IDs from the same events and show them as a single toast w/ a counter. Basically, that's how currency (Ancient Mana) toasts work. I've been testing this feature for quite some time, and it works almost perfectly, there are some issues on Blizz side T_T But, hopefully, I'll release it soon, but defo not in 70200.01.

**Comment by Funsponge** [comment]
Sounds good, thanks for the response. Look forward to seeing it in action.
