### ISSUE TITLE
70200.01 errors with transmog appearances

### ISSUE THREAD

**Issue by ceylina** [ls-/ls_Toasts#20]
1x Usage: local sources = C_TransmogCollection.GetAppearanceSources(appearanceID)
[C]: in function `GetAppearanceSources'
ls_Toasts\ls_Toasts-70200.01.lua:2617: in function <ls_Toasts\ls_Toasts.lua:2615>
ls_Toasts\ls_Toasts-70200.01.lua:2662: in function `?'
ls_Toasts\ls_Toasts-70200.01.lua:195: in function <ls_Toasts\ls_Toasts.lua:194>

Locals:
(*temporary) = "Usage: local sources = C_TransmogCollection.GetAppearanceSources(appearanceID)"

**Comment by ceylina** [comment]
Another error:

2x ls_Toasts\ls_Toasts-70200.01.lua:2494: Usage: GetProfessionInfo(index)
[C]: in function `GetProfessionInfo'
ls_Toasts\ls_Toasts-70200.01.lua:2494: in function <ls_Toasts\ls_Toasts.lua:2424>
ls_Toasts\ls_Toasts-70200.01.lua:2535: in function `?'
ls_Toasts\ls_Toasts-70200.01.lua:195: in function <ls_Toasts\ls_Toasts.lua:194>

Locals:
(*temporary) = true

**Comment by ls-** [comment]
Hmmmm, I defo fixed it....I guess I forgot to do push changes T_T

**Comment by ls-** [comment]
Oh, I pushed them, but only partially, FML 🔪

**Comment by ls-** [comment]
Fixed.

TY :D
