### ISSUE TITLE
add toast type: Loot (Quest)

### ISSUE THREAD

**Issue by killarny** [ls-/ls_Toasts#23]
I think it would be quite nice to be able to show a toast whenever quest loot is picked up.

**Comment by ls-** [comment]
It's a bit tricky. There's no special event that handles quest items' acquisition, but the ones that are shown in our inventory are handled by CHAT_MSG_LOOT, that's the event I use for common loot toasts.

So I may add a checkbox to `Loot (Common)` dropdown menu, e.g., `[ ] Quest`, to spawn toasts for quest items regardless of set item quality threshold. Quest items often are common (white) quality items.

I'll prob work on it this weekend. I have no time to do it now.

**Comment by ls-** [comment]
Dunno, if you're still using this addon, but here's some news regarding this feature request.

There's no API I can use to add this feature that allows me to track **all** looted quest items, so I requested its addition, however, it won't be added until after 7.3 T_T

There's `GetContainerItemQuestInfo` that allows to get necessary info for quest items that are shown in your bags, but there's no function that can provide the same info and uses item link and/or IDs.

**Comment by killarny** [comment]
Thanks for keeping it on your radar! I've taken a break from the game lately, but I definitely will be using this addon when I start playing again, and it's nice to know that it's still under active development.

I wonder if, in the meanwhile until a proper API call is added to let you track these, maybe whatever addons such as [XLoot](https://mods.curse.com/addons/wow/xloot) are doing to track quest item pickups would work?

![](https://media-curse.cursecdn.com/attachments/82/690/fba86cf22f5d14447cd7beae8c1ca684.png)

I haven't done really any development for WoW though, so I have no idea if this is helpful. Either way, thanks for the update!

**Comment by ls-** [comment]
I talked about stuff yesterday in IRC and kinda found a way to implement it now. Latest additions to WoW API are just poorly documented, had to ask Blizz dev for info on them :D 

What's shown in this screenshot, grey "quest" text, is called item class and subclass, the only issue w/ them is that they aren't 100% reliable, not so rarely these two params store some bogus values.

So I'll be using item class + subclass and recently added item binding type (there's a special one for majority of quest items) to catch 99% of quest items. There's one more thing I asked to add, but it won't be added w/ 7.3 T_T It's pushed to either 7.3.5 or even later patch/expansion.

**Comment by ls-** [comment]
Done! 🎉
