### ISSUE TITLE
Change which types of items appear?

### ISSUE THREAD

**Issue by gotmilk0112** [ls-/ls_Toasts#24]
As it is right now, it's popping up a toast window for almost every non-grey item that I loot. Is there a way to change that? I don't need toast windows for every quest item or bit of currency that I loot.

Ideally, I'd only want toasts for AP items, and rare/epic items.

**Comment by ls-** [comment]
So, if I understood correctly, you want me to add item type filter, right?

That's gonna be quite problematic. This whole item type/category thing is a bit wonky, many items have wrong item categories assigned to them, I know how bag addons handle it, what workarounds they use and that's defo not something want to do. It's not worth it, that's just waaaay too much code for such a minute feature.

There's item quality threshold for common/special loot toasts though, you can set it to rare and only toasts for blue, epic and legendary items will be shown.

**Comment by gotmilk0112** [comment]
Yeah, that's what I was looking for, to an extent: something that will put a filter on the quality. I didn't see any setting for that in the settings menu.

**Comment by ls-** [comment]
But it's there:
![](http://i.imgur.com/82YWqhW.png)

**Comment by gotmilk0112** [comment]
Where is that setting?

https://puu.sh/wmCBT/8251bb4051.png

**Comment by ls-** [comment]
There's a [+] next to ls: Toasts in the list of addons. Click it :p

**Comment by gotmilk0112** [comment]
I swear that thing wasn't there before.

**Comment by ls-** [comment]
It's ALWAYS there, it's there from the very first public release :D

**Comment by gotmilk0112** [comment]
Yeah, that was it. The + only appears after you click enable; that's why I didn't see it before.
