### ISSUE TITLE
Lua errors & no commands

### ISSUE THREAD

**Issue by pityu100** [ls-/ls_Toasts#26]
Hey there,

can you please check these lua errors? They pop up at login, and the commands /lst & /lstoasts does not work, with all addons disabled.

Version: 70300.07

 
Message: ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
Time: 02/16/18 11:29:03
Count: 1
Stack: ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
[C]: ?
[C]: in function `error'
...nterface\AddOns\SharedMedia\libs\LibStub\LibStub.lua:38: in function `LibStub'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:7: in main chunk

Locals:

 

-----

 

Message: Interface\AddOns\ls_Toasts\init.lua:306: Cannot find a library instance of "AceConfigDialog-3.0".
Time: 02/16/18 11:29:04
Count: 1
Stack: Interface\AddOns\ls_Toasts\init.lua:306: Cannot find a library instance of "AceConfigDialog-3.0".
[C]: ?
[C]: in function `error'
...nterface\AddOns\SharedMedia\libs\LibStub\LibStub.lua:38: in function `LibStub'
Interface\AddOns\ls_Toasts\init.lua:306: in function `func'
Interface\AddOns\ls_Toasts\core\core.lua:33: in function <Interface\AddOns\ls_Toasts\core\core.lua:31>

Locals:

**Comment by ls-** [comment]
Hm... I prob messed up lib loading order >_>

**Comment by ls-** [comment]
I'll release an update in couple of days because want to fix few other things first, and Curse is extremely slow when it comes to approval times anyway.

If you want to fix it ASAP, you can do it yourself by editing your [/embeds/_embeds.xml file](https://github.com/ls-/ls_Toasts/blob/master/embeds/_embeds.xml).
