### ISSUE TITLE
Getting LUA error when trying to load Is_Toasts

### ISSUE THREAD

**Issue by twiztiddreamz** [ls-/ls_Toasts#27]
Couldn't open Interface\AddOns\ls_Toasts-sqw\
Time: Thu Aug 30 07:06:34 2018
Count: 3
![istoastluawarning](https://user-images.githubusercontent.com/42836178/44848172-cf817200-ac23-11e8-8e5c-c7fdb1c0246a.JPG)

**Comment by ls-** [comment]
That's not ls_Toasts' issue, there's no such folder as ls_Toasts-sqw.

Quick googling showed that it's a skin for the addon.
