### ISSUE TITLE
No Error

### ISSUE THREAD

**Issue by FrogZilla083** [ls-/ls_Toasts#28]
Toasts is not showing scrapped loot anymore. It used to and was awesome. It could be I missed a setting or something. Please Help. Nice addon by the way.!

*update* looks like cloth items. I am still trying to figure it out.

**Comment by ls-** [comment]
Hm, weird, I'll look into it.

**Comment by ls-** [comment]
Fixed.

I need to check few more things and will release an update later.

**Comment by FrogZilla083** [comment]
Ok Thank You Very Much. I thought it was me. Appreciate your work and Merry Christmas!
