### ISSUE TITLE
currency toast also broken

### ISSUE THREAD

**Issue by Solor** [ls-/ls_Toasts#29]

**Comment by Solor** [comment]
nvm, my mistake.

**Comment by Solor** [comment]
sorry for bring this issue up again
currency toast doesn't work when I first login game, I have to disable and reenable it in the config panel, then it works fine, but when I reloadui, currency toast gone again, have to disable and reenable it again 😩 
only happens on currency
tried remove ls_Toasts SavedVariables file and reinstall it, no lucky

**Comment by ls-** [comment]
Hm, that's really weird, I've never experienced anything like that o_O

What exactly does happen when it doesn't work? Is it disabled in options after you reload? Do they stop popping up when you gain currency?

By any chance, do you use any addon that modifies chat messages like "You receive currency:" into something else? If you aren't sure, try doing `/dump CURRENCY_GAINED_MULTIPLE` and `/dump CURRENCY_GAINED` right after you log in and then post results here.

**Comment by Solor** [comment]
works like a charm, thanks 👍
