### ISSUE TITLE
Can't access Option panel

### ISSUE THREAD

**Issue by Seethez** [ls-/ls_Toasts#30]
I've just installed the newest version. /LST or /LSTOASTS does'nt work .. Can't see other ways to access it.
![Screenshot_86](https://user-images.githubusercontent.com/53628068/62400967-7df30d00-b581-11e9-8613-cd82c5028de4.png)

**Comment by ls-** [comment]
That's really weird. Are you that the addon is even enabled? Do you get any errors?

I've just tested w/ ONLY my toasts enabled, and everything worked just fine.
