### ISSUE TITLE
Gold threshold

### ISSUE THREAD

**Issue by Daeveren** [ls-/ls_Toasts#31]
With the latest addon update, I've just noticed the gold toast.
My suggestion is to add a threshold for each of the gold earned and gold spent. In its current state it's too spammy, showing up everytime I post something on AH. I'd probably set the treshold myself to 10k, with the purpose of only notifying me for big earnings/big spendings.

**Comment by ls-** [comment]
It being spammy was me fear as well, but I really want to have a toast that displays the accurate info. I might add the prev version of the gold toast as a separate entry.

Or I'll revert the whole thing its prev state, and then write a tiny personal addon that shows gold and/or currency changes.

**Comment by Daeveren** [comment]
Can't remember how the previous version was.
In my own use case, the new version made it more visible, since it's there in the middle of the screen on top of anything, even on top of the AH window. So for myself, it would be useful if it was a notification only used for rare/important moments - such as when you gain a big sum of gold or when you spend a big sum of gold (so in this case, perhaps a threshold of say 10k gold would have been a good match) -- seeing it showing up everytime I was posting on AH (I post many times per day) seemed spamy - not because it was showing many times in short time, but because it was showing, I'd go like "oh what is this?" just to realise that I've spent 1g posting something on AH.
Note, I already have an addon that shows on the screen the amount of gold I loot from the world/mail and also it shows it in chat too; currencies I see them via another addon.

**Comment by ls-** [comment]
Addressed in [80200.03](https://github.com/ls-/ls_Toasts/releases/tag/80200.03).
