### ISSUE TITLE
Ashran artifact fragment spam

### ISSUE THREAD

**Issue by Xathz** [ls-/ls_Toasts#32]
When you queue for the epic battleground Ashran and are near other players you get spammed with artifact fragments toasts every few seconds. You get the toasts as normal when you loot a fragment but it seems being around other players also shows a toast whether or not you looted one.

Version: 80200.05
Happens in older versions as well, not sure what version it started in.

**Comment by ls-** [comment]
Got it. I know what's going on.

**Comment by ls-** [comment]
K, now I got it.

Artefact fragments are one of those weird currencies whose actual and displayed amounts are different. For instance, if the actual amount is 1000 in the UI it'll be displayed as 10. Conquest points behave similarly.

The sad part is that different events and methods use different formats, and multipliers are hidden, no consistency whatsoever, so the only way to catch these weird exceptions is by spotting inconsistencies manually while playing the game >_>

**Comment by ls-** [comment]
Fixed.

You can pull it from GH or wait till I release an update within the next few days.
