### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by FrogZilla083** [ls-/ls_Toasts#33]
So it could just be my setup but I cannot move the location of Toasts. Even though on ElvUi I have it set to center. It still shows up in upper left hand corner of my screen. 
![WoWScrnShot_083119_140444](https://user-images.githubusercontent.com/42401035/64072194-b6593a00-cc58-11e9-83e3-0fd453e37439.jpg)

**Comment by FrogZilla083** [comment]
I am a pleb. You have your own anchor. I found it and fixed it. :P

**Comment by ls-** [comment]
Good job 👍

**Comment by ls-** [comment]
@FrogZilla083, on a side note, why don't you use one of included ElvUI skins?

![image](https://user-images.githubusercontent.com/2725970/64696703-4e60ea00-d4c9-11e9-88a9-0478f92bce3b.png)

**Comment by FrogZilla083** [comment]
LoL um it took me a minute to find how to get into your options. I did change it to Elvui (legacy) once I found your anchor. Well settings in general. I kept looking in elv setting and addons screen.
