### ISSUE TITLE
Attempt to unregister unknown event "ACHIEVEMENT_EARNED"

### ISSUE THREAD

**Issue by Pyrepenol** [ls-/ls_Toasts#34]
Started getting the error this morning, also can't pull up the settings.

> Message: Interface\AddOns\ls_Toasts\init.lua:311: Attempt to unregister unknown event "ACHIEVEMENT_EARNED"
> Time: Thu Sep  5 12:16:11 2019
> Count: 1
> Stack: Interface\AddOns\ls_Toasts\init.lua:311: Attempt to unregister unknown event "ACHIEVEMENT_EARNED"
> [C]: in function `UnregisterEvent'
> Interface\AddOns\ls_Toasts\init.lua:311: in function `func'
> Interface\AddOns\ls_Toasts\core\core.lua:42: in function <Interface\AddOns\ls_Toasts\core\core.lua:40>
> 
> Locals: (*temporary) = AlertFrame {
>  0 = <userdata>
>  SetSubSystemAnchorPriority = <function> defined @Interface\FrameXML\AlertFrames.lua:350
>  BuildQuestData = <function> defined @Interface\FrameXML\AlertFrames.lua:632
>  shouldQueueAlertsFlags = <table> {
>  }
>  SetJustification = <function> defined @Interface\FrameXML\AlertFrames.lua:377
>  CreateSubSystem = <function> defined @Interface\FrameXML\AlertFrames.lua:311
>  CreateQueuedSubSystem = <function> defined @Interface\FrameXML\AlertFrames.lua:328
>  SetEnabledFlag = <function> defined @Interface\FrameXML\AlertFrames.lua:277
>  SetVariablesLoaded = <function> defined @Interface\FrameXML\AlertFrames.lua:294
>  GetPointsForJustification = <function> defined @Interface\FrameXML\AlertFrames.lua:402
>  SetAlertsEnabled = <function> defined @Interface\FrameXML\AlertFrames.lua:299
>  BuildLFGRewardData = <function> defined @Interface\FrameXML\AlertFrames.lua:590
>  AreAlertsEnabled = <function> defined @Interface\FrameXML\AlertFrames.lua:303
>  AddQueuedAlertFrameSubSystem = <function> defined @Interface\FrameXML\AlertFrames.lua:338
>  AddAlertFrameSubSystem = <function> defined @Interface\FrameXML\AlertFrames.lua:342
>  GetJustification = <function> defined @Interface\FrameXML\AlertFrames.lua:384
>  anchorPrioritiesDirty = true
>  OnLoad = <function> defined @Interface\FrameXML\AlertFrames.lua:417
>  CleanAnchorPriorities = <function> defined @Interface\FrameXML\AlertFrames.lua:360
>  AddExternallyAnchoredSubSystem = <function> defined @Interface\FrameXML\AlertFrames.lua:318
>  ShouldSupressDungeonOrScenarioAlert = <function> defined @Interface\FrameXML\AlertFrames.lua:658
>  OnEvent = <function> defined @Interface\FrameXML\AlertFrames.lua:423
>  AddAutoAnchoredSubSystem = <function> defined @Interface\FrameXML\AlertFrames.lua:323
>  BuildScenarioRewardData = <function> defined @Interface\FrameXML\AlertFrames.lua:622
>  AddSimpleAlertFrameSubSystem = <function> defined @Interface\FrameXML\AlertFrames.lua:332
>  SetPlayerEnteredWorld = <function> defined @Interface\FrameXML\AlertFrames.lua:289
>  alertFrameSubSystems = <table> {
>  }
>  UpdateAnchors = <function> defined @Interface\FrameXML\AlertFrames.lua:368
>  ignoreFramePositionManager = true
>  AddAlertFrame = <function> defined @Interface\FrameXML\AlertFrames.lua:409
> }
> (*temporary) = "ACHIEVEMENT_EARNED"
>

**Comment by Pyrepenol** [comment]
I figured it out, I'm playing Classic and it seems that the Twitch client mistakenly updated to the version meant for vanilla rather than classic.

**Comment by ls-** [comment]
Good that you figured it out, CF's and Twitch client's Classic support leaves a lot to be desired.

Addon dev discord and IRC servers are filled w/ complaints atm T_T Even if you, as a dev, do everything according to curse/twitch guidelines, there's still a chance that the twitch client will pull the wrong version.
