### ISSUE TITLE
Error: RAF_ENTITLEMENT_DELIVERED

### ISSUE THREAD

**Issue by 40P3** [ls-/ls_Toasts#35]
Latest version of Is: Toasts
2x Attempt to register unknown event "RAF_ENTITLEMENT_DELIVERED"
[C]: ?
[C]: ?
ls_Toasts\core\core.lua:117: in function `Call'
ls_Toasts\core\core.lua:71: in function `RegisterEvent'
ls_Toasts\systems\store.lua:168: in function `Enable'
ls_Toasts\core\system.lua:75: in function `EnableAllSystems'
ls_Toasts\init.lua:325: in function `func'
ls_Toasts\core\core.lua:48: in function <ls_Toasts\core\core.lua:46>

**Comment by ls-** [comment]
You're using 80205.01, which is a version for 8.2.5, with 8.2.0 client. Downgrade to the latest 80200.* release.

**Comment by 40P3** [comment]
Haha, you're awesome thank you!
This is seriously the very first time when an addon version is built to the future release of wow update. :)))
Hats off!
Love your addon mate!
