### ISSUE TITLE
Got a error with is_toasts via bugsack

### ISSUE THREAD

**Issue by Rubyurek** [ls-/ls_Toasts#38]
1x [ADDON_ACTION_BLOCKED] AddOn 'ls_Toasts' hat versucht die geschützte Funktion 'CompactPartyFrame:unusedFunc()' aufzurufen.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `unusedFunc'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:160: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:57: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

**Comment by ls-** [comment]
Oof... Thanks, but there's no fix for it, I'll just have to wait and see. It can actually be unrelated to my addon at all. It's a taint, and error reports for those are unreliable, and fairly often innocent addons are blamed for it.
I won't be able to debug/fix it until I myself run into it, so I'll keep the issue open for now.
