### ISSUE TITLE
Reputation Toast

### ISSUE THREAD

**Issue by zalewskigrzegorz** [ls-/ls_Toasts#40]
I Use this addon since WoD and cannot live without it. There is a way to add toast for reputation changes?

**Comment by ls-** [comment]
Sup! XP and rep toasts have been suggested numerous times, but I'm really against adding those, they're VERY spammy, I honestly see no reason for adding those >_>
I should probably add it to my FAQ.

**Comment by Glaived** [comment]
Maybe make a system only at the change of state of a faction? (Friendly, exalted...)
