### ISSUE TITLE
WoWup issues 

### ISSUE THREAD

**Issue by kingreboot** [ls-/ls_Toasts#42]
Hi, I was trying to install your addon via WoWup and it installs all but the Retail Files. I am not sure why, as I don't understand the full details, but the WoWup discord has alot of people who do and will help.

**Comment by linaori** [comment]
If you use WowUp and install through github, it will install the wrong version as it just grabs the latest release. You can install it through Wago on WowUp though.

**Comment by kingreboot** [comment]
thanks for letting me know, but I must have found the wago version a while ago and been using

**Comment by ls-** [comment]
Good that it's all resolved now 😁
