### ISSUE TITLE
Archeology: receiving the fragments instead of spending

### ISSUE THREAD

**Issue by linaori** [ls-/ls_Toasts#43]
I think it should be showing that I lost the currency instead of gaining, but it would also be great if I could turn off the currency spending like with gold.

See recording: https://i.imgur.com/zfQ6EM7.mp4
Here with less "gain" due to fragment reducing cost: https://i.imgur.com/dZgNzDj.mp4

**Comment by ls-** [comment]
It's never meant to show fragment loss toasts. The module was last updated before Blizz added `Enum.CurrencySource`, so it still relied on values I put in there which by now are outdates.
