### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by WanderingFox** [ls-/ls_Toasts#45]
Hey there,

Is there a way to inject a custom toast (eg. extending the existing system via another addon etc)? It looks like all the methods needed are private inside of the addon namespace :(

**Comment by ls-** [comment]
Hi!

All of my toast "systems" are written as plugins, so if you need a reference take a look at something like [achievement toasts](https://github.com/ls-/ls_Toasts/blob/master/systems/achievement.lua), they're pretty simple. All you need are `E` (engine), `C` (config), and `L` (locales) tables, to access them just add `local E, C, L = unpack(ls_Toasts)` to your plugin's code.
