### ISSUE TITLE
10.0.2 lua error

### ISSUE THREAD

**Issue by lowpita** [ls-/ls_Toasts#49]
Hey. As of today's update for Retail (10.0.2) I'm getting this lua error whenever I load into the game:

1x Interface/AddOns/ls_Toasts/core/core.lua:247: attempt to call global 'IsDressableItem' (a nil value)
[string "@Interface/AddOns/ls_Toasts/core/core.lua"]:247: in function `DressUpLink'
[string "@Interface/AddOns/ls_Toasts/systems/loot_special.lua"]:21: in function <Interface/AddOns/ls_Toasts/systems/loot_special.lua:19>
[string "=[C]"]: ?

Locals:
self = <table> {
 GetScreenQuadrant = <function> defined @Interface/AddOns/ls_Toasts/core/core.lua:151
 GetToast = <function> defined @Interface/AddOns/ls_Toasts/core/toast.lua:788
 FindToast = <function> defined @Interface/AddOns/ls_Toasts/core/toast.lua:768
 RegisterOptions = <function> defined @Interface/AddOns/ls_Toasts/core/system.lua:102
 GetItemLevel = <function> defined @Interface/AddOns/ls_Toasts/core/core.lua:217
 UnregisterAllCallbacks = <function> defined @Interface/AddOns/Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 RegisterSkin = <function> defined @Interface/AddOns/ls_Toasts/core/skin.lua:18
 CHANGELOG = "- Added an option to show poor quality quality items via common loot toasts. Thanks to Faqar@GitHub.
- Added leaf ornaments to achievement toasts. I can't re-enable Blizz achievement toasts, so as a
  compromise I chose to make achievement toasts more unique. If you want them to stand out even more
  create a separate anchor to display them.
- Fixed an issue where repeatedly testing toasts and flushing the queue would sometimes lock up the
  addon.
- Fixed corrupt beautycase border texture. It worked, but baked-in shadows were messed up.
- Updated Traditional Chinese translation. Translated by BNS333@Curse.
"
 RegisterCallback = <function> defined @Interface/AddOns/Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 VER = <table> {
 }
 DressUpLink = <function> defined @Interface/AddOns/ls_Toasts/core/core.lua:241
 UnregisterCallback = <function> defined @Interface/AddOns/Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 RegisterSystem = <function> defined @Interface/AddOns/ls_Toasts/core/system.lua:20
 RegisterEvent = <function> defined @Interface/AddOns/ls_Toasts/core/core.lua:56
 SearchBagsForItemID = <function> defined @Interface/AddOns/ls_Toasts/core/core.lua:229
 UnregisterEvent = <function> defined @Interface/AddOns/ls_Toasts/core/core.lua:78
 SanitizeLink = <function> defined @Interface/AddOns/ls_Toasts/core/core.lua:128
}
link = "item:199383::::::::60:267::26:3:6652:7580:8936:1:28:2425:::::"
(*temporary) = nil
(*temporary) = "item:199383::::::::60:267::26:3:6652:7580:8936:1:28:2425:::::"
(*temporary) = "attempt to call global 'IsDressableItem' (a nil value)"
s_split = <function> defined =[C]:-1
C_PetJournal = <table> {
 GetPetTeamAverageLevel = <function> defined =[C]:-1
 PetIsFavorite = <function> defined =[C]:-1
 SetAllPetSourcesChecked = <function> defined =[C]:-1
 PetIsHurt = <function> defined =[C]:-1
 GetPetInfoBySpeciesID = <function> defined =[C]:-1
 PetNeedsFanfare = <function> defined =[C]:-1
 PickupSummonRandomPet = <function> defined =[C]:-1
 GetNumPetSources = <function> defined =[C]:-1
 GetNumPets = <function> defined =[C]:-1
 SetPetLoadOutInfo = <function> defined =[C]:-1
 SummonRandomPet = <function> defined =[C]:-1
 GetPetAbilityList = <function> defined =[C]:-1
 ClearSearchFilter = <function> defined =[C]:-1
 GetPetInfoTableByPetID = <function> defined =[C]:-1
 ReleasePetByID = <function> defined =[C]:-1
 PetIsUsable = <function> defined =[C]:-1
 FindPetIDByName = <function> defined =[C]:-1
 GetBattlePetLink = <function> defined =[C]:-1
 SetFavorite = <function> defined =[C]:-1
 GetPetModelSceneInfoBySpeciesID = <function> defined =[C]:-1
 PetIsRevoked = <function> defined =[C]:-1
 GetPetInfoByPetID = <function> defined =[C]:-1
 SetAbility = <function> defined =[C]:-1
 GetSummonedPetGUID = <function> defined =[C]:-1
 GetPetCooldownByGUID = <function> defined =[C]:-1
 GetPetStats = <function> defined =[C]:-1
 ClearRecentFanfares = <function> defined =[C]:-1
 PickupPet = <function> defined =[C]:-1
 GetPetSortParameter = <function> defined =[C]:-1
 GetDisplayIDByIndex = <function> defined =[C]:-1
 IsPetSourceChecked = <function> defined =[C]:-1
 SetCustomName = <function> defined =[C]:-1
 IsFilterChecked = <function> defined =[C]:-1
 IsFindBattleEnabled = <function> defined =[C]:-1
 GetNumCollectedInfo = <function> defined =[C]:-1
 GetPetSummonInfo = <function> defined =[C]:-1
 SetDefaultFilters = <function> defined =[C]:-1
 GetNumDisplays = <func

**Comment by ls-** [comment]
Thanks, I'll release an update a bit later when I get back home... 😥

**Comment by lowpita** [comment]
Also I think your addon is causing this lua error, as I tested without it and had no spams. This errors happens randomly whenever I log over and/or join a raid group without doing nothing like inspecting another player, opening the achievements tab or else: 

4x ...ns/Blizzard_AchievementUI/Blizzard_AchievementUI.lua:702: Usage: GetCategoryNumAchievements(categoryID, includeSuperceded)
[string "=[C]"]: in function `GetCategoryNumAchievements'
[string "@Interface/AddOns/Blizzard_AchievementUI/Blizzard_AchievementUI.lua"]:702: in function `AchievementFrameComparison_UpdateStatusBars'
[string "@Interface/AddOns/Blizzard_AchievementUI/Blizzard_AchievementUI.lua"]:2695: in function <...ns/Blizzard_AchievementUI/Blizzard_AchievementUI.lua:2691>

Locals:
(*temporary) = "summary"

**Comment by ls-** [comment]
This one is super weird, I've never seen anything like that. I looked into Blizz code and given when and how it's called, it'd be really Bizarre if it's my addon that caused it because I don't do anything that could lead to that event firing. I'll roll back some changes I made few weeks ago, but...

**Comment by ls-** [comment]
If it's in fact my addon that's causing it, then [this should do the trick](https://github.com/ls-/ls_Toasts/commit/83276716df5941753b7fc5519fc1f1fef1334cd4).
