### ISSUE TITLE
Wotlk 3.3.5a not working

### ISSUE THREAD

**Issue by Th3AnG3L** [ls-/ls_Toasts#50]
Hello i download the Ls_Toasts>wotlk/master>
But its not loaded in addons it not read it ingame no commands or Interface menu shows

**Comment by ls-** [comment]
![image](https://user-images.githubusercontent.com/2725970/210212572-37ab2667-aa52-4bf5-9ef9-6cf5a0c74b7b.png)

It works fine on 3.4.0. I don't support private servers, afaik, the original 3.3.5a and 3.4.0 have two different APIs with the later being a lot closer to what we have in retail wow.
