### ISSUE TITLE
Add new professions features to toasts

### ISSUE THREAD

**Issue by Kara-tatouille** [ls-/ls_Toasts#51]
Hi!
Dragonflight added reagent quality to most of the crafting reagents, it would be nice if Ls_Toasts showed reagent quality the same way when they're collected (there already exist a modifier adding stars to the toast thumbnail, but they don't seem to work for reagent gathering ? It would also be better to now use the same icons as the game)

As another feature, it would be nice to have more modifiers on different new crafting related procs (finesse, perception, inspiration, resourcefulness, multicraft)

**Comment by lowpita** [comment]
Hey. Bumping this. Would be awesome to have this enhancement.

**Comment by Taizunz** [comment]
Came here just to post this as a feature request, and I'm so happy to see I'm not the only one who would love this!

For reference, here's how gathering dragonflight materials looks like in LS: Toasts:
![e7sWZul](https://user-images.githubusercontent.com/15648000/215137905-5bc4920d-107d-4cea-a9fe-f19da805646e.png)

And here's what the icon with quality indicator (using ElvUI) in my bars looks like, and the same type of quality indicator that would be nice to have on the toasts from LS: Toasts as well:
![YTox3yN](https://user-images.githubusercontent.com/15648000/215138117-9a588331-d80d-400a-9bb1-1e143427728f.png)

**Comment by ls-** [comment]
Added in https://github.com/ls-/ls_Toasts/commit/4e97cb96cccea2f6550d9a80d75597523d380499
I legit forgot about it T_T I nearly forgot to add it again 😅

**Comment by ls-** [comment]
Reworked it, so it's more consistent across the UI. Also added support for crafted items, I kinda forgot about those 😒

![image](https://user-images.githubusercontent.com/2725970/215580007-5ac27d98-9b6e-47b5-b09c-8b545564eccd.png)

Now it should be properly done 🥳
