### ISSUE TITLE
garrison error lua

### ISSUE THREAD

**Issue by reyard** [ls-/ls_Toasts#52]
1x ls_Toasts/systems/garrison.lua:70: attempt to index field '?' (a nil value)
[string "@ls_Toasts/systems/garrison.lua"]:70: in function `func'
[string "@ls_Toasts/core/core.lua"]:35: in function <ls_Toasts/core/core.lua:33>

Locals:
followerTypeID = 123
missionID = 2205
garrisonType = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
getGarrisonTypeByFollowerType = <function> defined @ls_Toasts/systems/garrison.lua:21
C = <table> {
 db = <table> {
 }
 options = <table> {
 }
}
typeToKey = <table> {
 3 = "garrison_7_0"
 2 = "garrison_6_0"
 9 = "garrison_8_0"
 111 = "garrison_9_0"
}
MissionToast_SetUp = <function> defined @ls_Toasts/systems/garrison.lua:33

**Comment by zaphon** [comment]
FYI this is due to Blizzard Changing the names of the ENUMS for Garrison Followers and Garrison Types.

**Comment by zaphon** [comment]
[garrison.zip](https://github.com/ls-/ls_Toasts/files/11044573/garrison.zip)

Attached is a zip file containing garrison.lua which goes in Interface\AddOns\ls_Toasts\systems and fixes the issue above.

**Comment by ls-** [comment]
Fixed in 5dc127e10e5f589b64e0bf50e11f60229068ecc8. Sorry, couldn't do that earlier 😢
