### ISSUE TITLE
Blizzard skin on EVERYTHING?

### ISSUE THREAD

**Issue by Smekolini** [ls-/ls_Toasts#53]
I know it's impossible to enable the default blizzard skin for only achievements, but is it possible to add a skin that makes everything have the default achievement look?

The default achievement toast is almost too nostalgic to get rid of for me, but everything else about this addon is so perfect

**Comment by ls-** [comment]
With the next update I'll be adding a new skin called "Blizz Achievement" that has that two tone background. Although it's a bit more desaturated.

![image](https://github.com/ls-/ls_Toasts/assets/2725970/e6a21d51-c4ba-467e-a076-3358ee33324a)

I might tweak it later depending on the feedback.

**Comment by Smekolini** [comment]
Thanks! But are there any plans to add this to Classic aswell?

**Comment by ls-** [comment]
Oh, I don't play classic, so I completely forgot about it T_T I'll release an update when 3.4.2 goes live 🤔 Or did you mean vanilla?

**Comment by Smekolini** [comment]
Okay sweet! I meant WOTLK yea :)
