### ISSUE TITLE
Lua Error in 10.1

### ISSUE THREAD

**Issue by wheatbread** [ls-/ls_Toasts#54]
Hi, getting the following error in 10.1 on retail, using version 100100.01:

`8x ls_Toasts/systems/world.lua:109: attempt to compare number with nil
[string "@ls_Toasts/systems/world.lua"]:109: in function <ls_Toasts/systems/world.lua:30>
[string "@ls_Toasts/systems/world.lua"]:167: in function <ls_Toasts/systems/world.lua:158>
[string "@ls_Toasts/systems/world.lua"]:181: in function `func'
[string "@ls_Toasts/core/core.lua"]:35: in function <ls_Toasts/core/core.lua:33>

Locals:
event = "QUEST_TURNED_IN"
isUpdate = false
questID = 75705
name = "Monument Maintenance"
moneyReward = 0
xpReward = 0
numCurrencyRewards = 0
itemReward = nil
toast = LSToast1 {
 0 = <userdata>
 IconText2 = FontString {
 }
 BG = Texture {
 }
 TextBG = Texture {
 }
 Arrow5 = Texture {
 }
 IconBorder = <table> {
 }
 SetLeavesVertexColor = <function> defined @ls_Toasts/core/toast.lua:500
 IconHL = Texture {
 }
 Bonus = Texture {
 }
 Arrow4 = Texture {
 }
 Leaves = <table> {
 }
 Slot1 = Frame {
 }
 IconText1BG = Texture {
 }
 Release = <function> defined @ls_Toasts/core/toast.lua:320
 Spawn = <function> defined @ls_Toasts/core/toast.lua:305
 ShowLeaves = <function> defined @ls_Toasts/core/toast.lua:484
 Glow = Texture {
 }
 Slot5 = Frame {
 }
 Arrow3 = Texture {
 }
 Skull = Texture {
 }
 Dragon = Texture {
 }
 SetBackground = <function> defined @ls_Toasts/core/toast.lua:378
 Border = <table> {
 }
 _data = <table> {
 }
 AnimIn = AnimationGroup {
 }
 Arrow1 = Texture {
 }
 Icon = Texture {
 }
 AreLeavesShown = <function> defined @ls_Toasts/core/toast.lua:496
 IconParent = Frame {
 }
 Slot3 = Frame {
 }
 IconText1 = FontString {
 }
 Slot2 = Frame {
 }
 AnimArrows = AnimationGroup {
 }
 IconText3BG = Texture {
 }
 Slot4 = Frame {
 }
 HideLeaves = <function> defined @ls_Toasts/core/toast.lua:490
 Recycle = <function> defined @ls_Toasts/core/toast.lua:320
 ShouldHideLeaves = <function> defined @ls_Toasts/core/toast.lua:506
 Title = FontString {
 }
 IconText3 = FontString {
 }
 Shine = Texture {
 }
 AnimOut = AnimationGroup {
 }
 Text = FontString {
 }
 Arrow2 = Texture {
 }
}
isNew = true
isQueued = nil
usedSlots = 0
info = <table> {
 tagID = 283
 tagName = "Bonus Ojective with Completion Toast"
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = "Interface\Icons\Achievement_Quests_Completed_TwilightHighlands"
(*temporary) = true
(*temporary) = true
(*temporary) = nil
(*temporary) = LSToast1 {
 0 = <userdata>
 IconText2 = FontString {
 }
 BG = Texture {
 }
 TextBG = Texture {
 }
 Arrow5 = Texture {
 }
 IconBorder = <table> {
 }
 SetLeavesVertexColor = <function> defined @ls_Toasts/core/toast.lua:500
 IconHL = Texture {
 }
 Bonus = Texture {
 }
 Arrow4 = Texture {
 }
 Leaves = <table> {
 }
 Slot1 = Frame {
 }
 IconText1BG = Texture {
 }
 Release = <function> defined @ls_Toasts/core/toast.lua:320
 Spawn = <function> defined @ls_Toasts/core/toast.lua:305
 ShowLeaves = <function> defined @ls_Toasts/core/toast.lua:484
 Glow = Texture {
 }
 Slot5 = Frame {
 }
 Arrow3 = Texture {
 }
 Skull = Texture {
 }
 Dragon = Texture {
 }
 SetBackground = <function> defined @ls_Toasts/core/toast.lua:378
 Border = <table> {
 }
 _data = <table> {
 }
 AnimIn = AnimationGroup {
 }
 Arrow1 = Texture {
 }
 Icon = Texture {
 }
 AreLeavesShown = <function> defined @ls_Toasts/core/toast.lua:496
 IconParent = Frame {
 }
 Slot3 = Frame {
 }
 IconText1 = FontString {
 }
 Slot2 = Frame {
 }
 AnimArrows = AnimationGroup {
 }
 IconText3BG = Texture {
 }
 Slot4 = Frame {
 }
 HideLeaves = <function> defined @ls_Toasts/core/toast.lua:490
 Recycle = <function> defined @ls_Toasts/core/toast.lua:320
 ShouldHideLeaves = <function> defined @ls_Toasts/core/toast.lua:506
 Title = FontString {
 }
 IconText3 = FontString {
 }
 Shine = Texture {
 }
 AnimOut = AnimationGroup {
 }
 Text = FontString {
 }
 Arrow2 = Texture {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
E = <table> {
 GetScreenQuadrant = <function> defined @ls_Toasts/core/core.lua:138
 RegisterSkin = <function> defined @ls_Toasts/core/skin.lua:15
 VER = <table> {
 }
 RegisterEvent = <function> defined @ls_Toasts/core/core.lua:43
 GetToast = <function> defined @AddOns`

**Comment by ls-** [comment]
Fixed in: 27f272b7b39c70208fd0746369a6fdfd16d54448 😑
