### ISSUE TITLE
Feature request: add display of total item count

### ISSUE THREAD

**Issue by raptormama** [ls-/ls_Toasts#55]
Would love to have a selectable option to display total item count alongside the count of items just looted.

For example, if catching a bass while I've already got ten of the same fish in my bag, seeing something like "+1 (11)" on the toast would be helpful.

**Comment by ls-** [comment]
Hi! 

I'm sorry, but no 😓 If that's absolutely something you want to see, I suggest using an addon that adds total counts to tooltips, that's what I do.
