### ISSUE TITLE
Feature Request: Separate personal and guild achievement toast types

### ISSUE THREAD

**Issue by Taizunz** [ls-/ls_Toasts#59]
I'd love to be able to disable guild achievements as there appears to be a UI bug where some old guild achievements re-pop from time to time. 
At the moment this doesn't appear to be possible in LS Toasts as guild and personal achievements aren't separated, hence I'm requesting the separation of these so each type can be configured to the users liking.

**Comment by ls-** [comment]
Fixed, should be up with the next update, but not today.
