### ISSUE TITLE
Currency Issue in Cata

### ISSUE THREAD

**Issue by ImMooky** [ls-/ls_Toasts#63]
Hi There,

it seems the currency is way out of scale... I get 200 honor and it will show thousands and so on... doing this with all forms of currency. 

I have attempted to re-install to see if that solves with no luck. Thank you!

**Comment by ls-** [comment]
Ugh, I just checked Blizz code for classic cata and found this:

```lua
if GetClassicExpansionLevel() >= LE_EXPANSION_CATACLYSM then
	honor = honor / 100;
end
```

So they're manually adjusting the honour value in their UI code. Bizarre...

**Comment by ls-** [comment]
K, should be fixed. I'll release an update a bit later.
