### ISSUE TITLE
Total count

### ISSUE THREAD

**Issue by Sticklord** [ls-/ls_Toasts#7]
Hey, great addon! One of those that I didn't know I needed until it was downloaded.

I'm now using this instead of the chat log (using it for all items), and felt like it would a good addition to show total count of an item aswell somehow.

**Comment by ls-** [comment]
Hey! Thank you 😁 

TBH, I was thinking about adding total count to a toast even before addon's release, but I couldn't find a place for it. And I really didn't want to do it blizz style, cuz it looks meh.... But I might have to, if I decide to add it.

![image](https://cloud.githubusercontent.com/assets/2725970/18621446/cac96aa2-7e4d-11e6-9719-d3fb27d46920.png)

We'll see... For now, I'd suggest using any addon that adds total item count to item's tooltip, that's what I do 😞
