### ISSUE TITLE
Group Finder joining Battleground triggers Error

### ISSUE THREAD

**Issue by greven** [ls-/ls_Toasts#8]
Whenever I try to join a BG with the Group Finder the following error triggers. Blizzard warns about disabling the addon, actually it is the only way to join a BG.

--------

`3x [ADDON_ACTION_FORBIDDEN] AddOn 'ls_Toasts' tried to call the protected function 'JoinBattlefield()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function "JoinBattlefield"
Blizzard_PVPUI\Blizzard_PVPUI-1.0.lua:551: in function "HonorFrame_Queue"
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
nil`

**Comment by ls-** [comment]
Hi!

Whoa, that's quite strange... I'm PvPer, doing BGs all the time, and I've never seen anything like that. TBH, it might be one of those random taints that occur once in a while and then disappear after UI reload.

 I'll look into it, if I ever encounter it...

**Comment by greven** [comment]
Reload didn't fix it.
But I'll try disabling other addons to try to isolate it. It blames ls_toasts for the taint, which is quite odd.
I'll report back.

**Comment by ls-** [comment]
That's really odd, cuz ls_toasts doesn't do anything to HonorFrame or related frames, like at all.

BTW, if this bug persists after you disable other addons, try commenting out [this line](https://github.com/ls-/ls_Toasts/blob/master/ls_Toasts.lua#L3085). That's the only place, where ls_toasts 100% taints Blizz UI. For example, existance of in-game config is the reason for infamous compact frame taint T_T

**Comment by greven** [comment]
Hi ls-,

Deleted all ls_toasts cache, no cigar.
Commenting out the CreateConfigPanel() did it. Somehow that is tainting the UI, what is odd is why does it happens to me and not you.

**Comment by ls-** [comment]
TBH, I have no idea, that's really REALLY old Blizz bug. IIRC, it's been there since WotLK. Addon 100% taints some elements of default UI, if you create in-game config in Interface-AddOns section, a.k.a the way Blizz wants us to create configs.

I've been testing a small fix lately, it's quite straightforward, addon will create config panel, only when user uses /lstoasts command to open config.

I'll push it in few minutes. But this way I'll be able to avoid many taints.

**Comment by ls-** [comment]
I hope https://github.com/ls-/ls_Toasts/commit/fae8234a66f609dffef221cde8a46474c8856412 will fix it 😁

**Comment by greven** [comment]
It surely did fix it!
Thanks a lot ls- for the quick fix, your. :)
