### ISSUE TITLE
[REQUEST] Rarity Toast support

### ISSUE THREAD

**Issue by Homaxz** [ls-/ls_Toasts#9]
Hi and thanks for your great AddOn.

I want to request rarity support, here is a example, in the top left: http://i.imgur.com/XGHE0K7.jpg 

Kind regards

**Comment by ls-** [comment]
Hi! Thanks 😁 

Do you mean that Swift Ram toast created by another addon? There's a whole system + db behind such things, that's outside the scope of my addon, hence my answer is **no**.

**Comment by Homaxz** [comment]
Hi, yeah this Toast is created by the Addon "Rarity". 

Not too big of an issue, thanks for responding :)

**Comment by ls-** [comment]
No problem.

Integration w/ other addons is a bit complicated thingy. I _may_ implement interface for other addons to add their own toasts, but that's a really REALLY long-term plan 😒 But who knows...

Anyways, thank you for your suggestion, sorry for negative reply, hehe. Closing this PR.
